/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../../routes/__root'
import { Route as UnauthorizedRouteImport } from './../../../routes/unauthorized'
import { Route as ResetPasswordRouteImport } from './../../../routes/reset-password'
import { Route as LoginRouteImport } from './../../../routes/login'
import { Route as Data_collectorRouteImport } from './../../../routes/data_collector'
import { Route as AdminRouteImport } from './../../../routes/admin'
import { Route as ManagerRouteImport } from './../../../routes/_manager'
import { Route as IndexRouteImport } from './../../../routes/index'
import { Route as AdminOverviewRouteImport } from './../../../routes/admin/_overview'
import { Route as AdminOperationsRouteImport } from './../../../routes/admin/_operations'
import { Route as AdminConfigurationRouteImport } from './../../../routes/admin/_configuration'
import { Route as AdminAccessControlRouteImport } from './../../../routes/admin/_accessControl'
import { Route as ManagerSandboxRouteImport } from './../../../routes/_manager/sandbox'
import { Route as ManagerFormsRouteImport } from './../../../routes/_manager/forms'
import { Route as ManagerOverviewRouteImport } from './../../../routes/_manager/_overview'
import { Route as ManagerDataRouteImport } from './../../../routes/_manager/_data'
import { Route as ManagerAnalyticsRouteImport } from './../../../routes/_manager/_analytics'
import { Route as AdminOverviewDashboardRouteImport } from './../../../routes/admin/_overview/dashboard'
import { Route as AdminOperationsBackupRouteImport } from './../../../routes/admin/_operations/backup'
import { Route as AdminOperationsAuditLogsRouteImport } from './../../../routes/admin/_operations/audit-logs'
import { Route as AdminOperationsActivityLogsRouteImport } from './../../../routes/admin/_operations/activity-logs'
import { Route as AdminConfigurationSettingsRouteImport } from './../../../routes/admin/_configuration/settings'
import { Route as AdminAccessControlUserManagementRouteImport } from './../../../routes/admin/_accessControl/user-management'
import { Route as ManagerFormsFormTypeRouteImport } from './../../../routes/_manager/forms/$formType'
import { Route as ManagerOverviewMonitoredFieldsRouteImport } from './../../../routes/_manager/_overview/monitored-fields'
import { Route as ManagerOverviewDashboardRouteImport } from './../../../routes/_manager/_overview/dashboard'
import { Route as ManagerOverviewCollectionRouteImport } from './../../../routes/_manager/_overview/collection'
import { Route as ManagerDataMfidRouteImport } from './../../../routes/_manager/_data/mfid'
import { Route as ManagerDataImportRouteImport } from './../../../routes/_manager/_data/import'
import { Route as ManagerAnalyticsPredictiveRouteImport } from './../../../routes/_manager/_analytics/predictive'
import { Route as ManagerAnalyticsFormsAnalyticsRouteImport } from './../../../routes/_manager/_analytics/forms-analytics'
import { Route as ManagerAnalyticsDescriptiveRouteImport } from './../../../routes/_manager/_analytics/descriptive'
import { Route as ManagerAnalyticsComparativeRouteImport } from './../../../routes/_manager/_analytics/comparative'
import { Route as ManagerFormsFormTypeIndexRouteImport } from './../../../routes/_manager/forms/$formType.index'
import { Route as ManagerDataMfidIndexRouteImport } from './../../../routes/_manager/_data/mfid/index'
import { Route as ManagerFormsFormTypeIdRouteImport } from './../../../routes/_manager/forms/$formType.$id'
import { Route as ManagerDataMfidMfidRouteImport } from './../../../routes/_manager/_data/mfid/$mfid'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Data_collectorRoute = Data_collectorRouteImport.update({
  id: '/data_collector',
  path: '/data_collector',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/_manager',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/_overview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOperationsRoute = AdminOperationsRouteImport.update({
  id: '/_operations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigurationRoute = AdminConfigurationRouteImport.update({
  id: '/_configuration',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccessControlRoute = AdminAccessControlRouteImport.update({
  id: '/_accessControl',
  getParentRoute: () => AdminRoute,
} as any)
const ManagerSandboxRoute = ManagerSandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerFormsRoute = ManagerFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerOverviewRoute = ManagerOverviewRouteImport.update({
  id: '/_overview',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerDataRoute = ManagerDataRouteImport.update({
  id: '/_data',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerAnalyticsRoute = ManagerAnalyticsRouteImport.update({
  id: '/_analytics',
  getParentRoute: () => ManagerRoute,
} as any)
const AdminOverviewDashboardRoute = AdminOverviewDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminOverviewRoute,
} as any)
const AdminOperationsBackupRoute = AdminOperationsBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AdminOperationsRoute,
} as any)
const AdminOperationsAuditLogsRoute =
  AdminOperationsAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => AdminOperationsRoute,
  } as any)
const AdminOperationsActivityLogsRoute =
  AdminOperationsActivityLogsRouteImport.update({
    id: '/activity-logs',
    path: '/activity-logs',
    getParentRoute: () => AdminOperationsRoute,
  } as any)
const AdminConfigurationSettingsRoute =
  AdminConfigurationSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AdminConfigurationRoute,
  } as any)
const AdminAccessControlUserManagementRoute =
  AdminAccessControlUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => AdminAccessControlRoute,
  } as any)
const ManagerFormsFormTypeRoute = ManagerFormsFormTypeRouteImport.update({
  id: '/$formType',
  path: '/$formType',
  getParentRoute: () => ManagerFormsRoute,
} as any)
const ManagerOverviewMonitoredFieldsRoute =
  ManagerOverviewMonitoredFieldsRouteImport.update({
    id: '/monitored-fields',
    path: '/monitored-fields',
    getParentRoute: () => ManagerOverviewRoute,
  } as any)
const ManagerOverviewDashboardRoute =
  ManagerOverviewDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => ManagerOverviewRoute,
  } as any)
const ManagerOverviewCollectionRoute =
  ManagerOverviewCollectionRouteImport.update({
    id: '/collection',
    path: '/collection',
    getParentRoute: () => ManagerOverviewRoute,
  } as any)
const ManagerDataMfidRoute = ManagerDataMfidRouteImport.update({
  id: '/mfid',
  path: '/mfid',
  getParentRoute: () => ManagerDataRoute,
} as any)
const ManagerDataImportRoute = ManagerDataImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => ManagerDataRoute,
} as any)
const ManagerAnalyticsPredictiveRoute =
  ManagerAnalyticsPredictiveRouteImport.update({
    id: '/predictive',
    path: '/predictive',
    getParentRoute: () => ManagerAnalyticsRoute,
  } as any)
const ManagerAnalyticsFormsAnalyticsRoute =
  ManagerAnalyticsFormsAnalyticsRouteImport.update({
    id: '/forms-analytics',
    path: '/forms-analytics',
    getParentRoute: () => ManagerAnalyticsRoute,
  } as any)
const ManagerAnalyticsDescriptiveRoute =
  ManagerAnalyticsDescriptiveRouteImport.update({
    id: '/descriptive',
    path: '/descriptive',
    getParentRoute: () => ManagerAnalyticsRoute,
  } as any)
const ManagerAnalyticsComparativeRoute =
  ManagerAnalyticsComparativeRouteImport.update({
    id: '/comparative',
    path: '/comparative',
    getParentRoute: () => ManagerAnalyticsRoute,
  } as any)
const ManagerFormsFormTypeIndexRoute =
  ManagerFormsFormTypeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ManagerFormsFormTypeRoute,
  } as any)
const ManagerDataMfidIndexRoute = ManagerDataMfidIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerDataMfidRoute,
} as any)
const ManagerFormsFormTypeIdRoute = ManagerFormsFormTypeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ManagerFormsFormTypeRoute,
} as any)
const ManagerDataMfidMfidRoute = ManagerDataMfidMfidRouteImport.update({
  id: '/$mfid',
  path: '/$mfid',
  getParentRoute: () => ManagerDataMfidRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminOverviewRouteWithChildren
  '/data_collector': typeof Data_collectorRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/forms': typeof ManagerFormsRouteWithChildren
  '/sandbox': typeof ManagerSandboxRoute
  '/comparative': typeof ManagerAnalyticsComparativeRoute
  '/descriptive': typeof ManagerAnalyticsDescriptiveRoute
  '/forms-analytics': typeof ManagerAnalyticsFormsAnalyticsRoute
  '/predictive': typeof ManagerAnalyticsPredictiveRoute
  '/import': typeof ManagerDataImportRoute
  '/mfid': typeof ManagerDataMfidRouteWithChildren
  '/collection': typeof ManagerOverviewCollectionRoute
  '/dashboard': typeof ManagerOverviewDashboardRoute
  '/monitored-fields': typeof ManagerOverviewMonitoredFieldsRoute
  '/forms/$formType': typeof ManagerFormsFormTypeRouteWithChildren
  '/admin/user-management': typeof AdminAccessControlUserManagementRoute
  '/admin/settings': typeof AdminConfigurationSettingsRoute
  '/admin/activity-logs': typeof AdminOperationsActivityLogsRoute
  '/admin/audit-logs': typeof AdminOperationsAuditLogsRoute
  '/admin/backup': typeof AdminOperationsBackupRoute
  '/admin/dashboard': typeof AdminOverviewDashboardRoute
  '/mfid/$mfid': typeof ManagerDataMfidMfidRoute
  '/forms/$formType/$id': typeof ManagerFormsFormTypeIdRoute
  '/mfid/': typeof ManagerDataMfidIndexRoute
  '/forms/$formType/': typeof ManagerFormsFormTypeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminOverviewRouteWithChildren
  '/data_collector': typeof Data_collectorRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/forms': typeof ManagerFormsRouteWithChildren
  '/sandbox': typeof ManagerSandboxRoute
  '/comparative': typeof ManagerAnalyticsComparativeRoute
  '/descriptive': typeof ManagerAnalyticsDescriptiveRoute
  '/forms-analytics': typeof ManagerAnalyticsFormsAnalyticsRoute
  '/predictive': typeof ManagerAnalyticsPredictiveRoute
  '/import': typeof ManagerDataImportRoute
  '/collection': typeof ManagerOverviewCollectionRoute
  '/dashboard': typeof ManagerOverviewDashboardRoute
  '/monitored-fields': typeof ManagerOverviewMonitoredFieldsRoute
  '/admin/user-management': typeof AdminAccessControlUserManagementRoute
  '/admin/settings': typeof AdminConfigurationSettingsRoute
  '/admin/activity-logs': typeof AdminOperationsActivityLogsRoute
  '/admin/audit-logs': typeof AdminOperationsAuditLogsRoute
  '/admin/backup': typeof AdminOperationsBackupRoute
  '/admin/dashboard': typeof AdminOverviewDashboardRoute
  '/mfid/$mfid': typeof ManagerDataMfidMfidRoute
  '/forms/$formType/$id': typeof ManagerFormsFormTypeIdRoute
  '/mfid': typeof ManagerDataMfidIndexRoute
  '/forms/$formType': typeof ManagerFormsFormTypeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_manager': typeof ManagerRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/data_collector': typeof Data_collectorRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_manager/_analytics': typeof ManagerAnalyticsRouteWithChildren
  '/_manager/_data': typeof ManagerDataRouteWithChildren
  '/_manager/_overview': typeof ManagerOverviewRouteWithChildren
  '/_manager/forms': typeof ManagerFormsRouteWithChildren
  '/_manager/sandbox': typeof ManagerSandboxRoute
  '/admin/_accessControl': typeof AdminAccessControlRouteWithChildren
  '/admin/_configuration': typeof AdminConfigurationRouteWithChildren
  '/admin/_operations': typeof AdminOperationsRouteWithChildren
  '/admin/_overview': typeof AdminOverviewRouteWithChildren
  '/_manager/_analytics/comparative': typeof ManagerAnalyticsComparativeRoute
  '/_manager/_analytics/descriptive': typeof ManagerAnalyticsDescriptiveRoute
  '/_manager/_analytics/forms-analytics': typeof ManagerAnalyticsFormsAnalyticsRoute
  '/_manager/_analytics/predictive': typeof ManagerAnalyticsPredictiveRoute
  '/_manager/_data/import': typeof ManagerDataImportRoute
  '/_manager/_data/mfid': typeof ManagerDataMfidRouteWithChildren
  '/_manager/_overview/collection': typeof ManagerOverviewCollectionRoute
  '/_manager/_overview/dashboard': typeof ManagerOverviewDashboardRoute
  '/_manager/_overview/monitored-fields': typeof ManagerOverviewMonitoredFieldsRoute
  '/_manager/forms/$formType': typeof ManagerFormsFormTypeRouteWithChildren
  '/admin/_accessControl/user-management': typeof AdminAccessControlUserManagementRoute
  '/admin/_configuration/settings': typeof AdminConfigurationSettingsRoute
  '/admin/_operations/activity-logs': typeof AdminOperationsActivityLogsRoute
  '/admin/_operations/audit-logs': typeof AdminOperationsAuditLogsRoute
  '/admin/_operations/backup': typeof AdminOperationsBackupRoute
  '/admin/_overview/dashboard': typeof AdminOverviewDashboardRoute
  '/_manager/_data/mfid/$mfid': typeof ManagerDataMfidMfidRoute
  '/_manager/forms/$formType/$id': typeof ManagerFormsFormTypeIdRoute
  '/_manager/_data/mfid/': typeof ManagerDataMfidIndexRoute
  '/_manager/forms/$formType/': typeof ManagerFormsFormTypeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/data_collector'
    | '/login'
    | '/reset-password'
    | '/unauthorized'
    | '/forms'
    | '/sandbox'
    | '/comparative'
    | '/descriptive'
    | '/forms-analytics'
    | '/predictive'
    | '/import'
    | '/mfid'
    | '/collection'
    | '/dashboard'
    | '/monitored-fields'
    | '/forms/$formType'
    | '/admin/user-management'
    | '/admin/settings'
    | '/admin/activity-logs'
    | '/admin/audit-logs'
    | '/admin/backup'
    | '/admin/dashboard'
    | '/mfid/$mfid'
    | '/forms/$formType/$id'
    | '/mfid/'
    | '/forms/$formType/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/data_collector'
    | '/login'
    | '/reset-password'
    | '/unauthorized'
    | '/forms'
    | '/sandbox'
    | '/comparative'
    | '/descriptive'
    | '/forms-analytics'
    | '/predictive'
    | '/import'
    | '/collection'
    | '/dashboard'
    | '/monitored-fields'
    | '/admin/user-management'
    | '/admin/settings'
    | '/admin/activity-logs'
    | '/admin/audit-logs'
    | '/admin/backup'
    | '/admin/dashboard'
    | '/mfid/$mfid'
    | '/forms/$formType/$id'
    | '/mfid'
    | '/forms/$formType'
  id:
    | '__root__'
    | '/'
    | '/_manager'
    | '/admin'
    | '/data_collector'
    | '/login'
    | '/reset-password'
    | '/unauthorized'
    | '/_manager/_analytics'
    | '/_manager/_data'
    | '/_manager/_overview'
    | '/_manager/forms'
    | '/_manager/sandbox'
    | '/admin/_accessControl'
    | '/admin/_configuration'
    | '/admin/_operations'
    | '/admin/_overview'
    | '/_manager/_analytics/comparative'
    | '/_manager/_analytics/descriptive'
    | '/_manager/_analytics/forms-analytics'
    | '/_manager/_analytics/predictive'
    | '/_manager/_data/import'
    | '/_manager/_data/mfid'
    | '/_manager/_overview/collection'
    | '/_manager/_overview/dashboard'
    | '/_manager/_overview/monitored-fields'
    | '/_manager/forms/$formType'
    | '/admin/_accessControl/user-management'
    | '/admin/_configuration/settings'
    | '/admin/_operations/activity-logs'
    | '/admin/_operations/audit-logs'
    | '/admin/_operations/backup'
    | '/admin/_overview/dashboard'
    | '/_manager/_data/mfid/$mfid'
    | '/_manager/forms/$formType/$id'
    | '/_manager/_data/mfid/'
    | '/_manager/forms/$formType/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManagerRoute: typeof ManagerRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  Data_collectorRoute: typeof Data_collectorRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data_collector': {
      id: '/data_collector'
      path: '/data_collector'
      fullPath: '/data_collector'
      preLoaderRoute: typeof Data_collectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_manager': {
      id: '/_manager'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_overview': {
      id: '/admin/_overview'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_operations': {
      id: '/admin/_operations'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminOperationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_configuration': {
      id: '/admin/_configuration'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminConfigurationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_accessControl': {
      id: '/admin/_accessControl'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAccessControlRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_manager/sandbox': {
      id: '/_manager/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof ManagerSandboxRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/_manager/forms': {
      id: '/_manager/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof ManagerFormsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/_manager/_overview': {
      id: '/_manager/_overview'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ManagerOverviewRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/_manager/_data': {
      id: '/_manager/_data'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ManagerDataRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/_manager/_analytics': {
      id: '/_manager/_analytics'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ManagerAnalyticsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/admin/_overview/dashboard': {
      id: '/admin/_overview/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminOverviewDashboardRouteImport
      parentRoute: typeof AdminOverviewRoute
    }
    '/admin/_operations/backup': {
      id: '/admin/_operations/backup'
      path: '/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AdminOperationsBackupRouteImport
      parentRoute: typeof AdminOperationsRoute
    }
    '/admin/_operations/audit-logs': {
      id: '/admin/_operations/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminOperationsAuditLogsRouteImport
      parentRoute: typeof AdminOperationsRoute
    }
    '/admin/_operations/activity-logs': {
      id: '/admin/_operations/activity-logs'
      path: '/activity-logs'
      fullPath: '/admin/activity-logs'
      preLoaderRoute: typeof AdminOperationsActivityLogsRouteImport
      parentRoute: typeof AdminOperationsRoute
    }
    '/admin/_configuration/settings': {
      id: '/admin/_configuration/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminConfigurationSettingsRouteImport
      parentRoute: typeof AdminConfigurationRoute
    }
    '/admin/_accessControl/user-management': {
      id: '/admin/_accessControl/user-management'
      path: '/user-management'
      fullPath: '/admin/user-management'
      preLoaderRoute: typeof AdminAccessControlUserManagementRouteImport
      parentRoute: typeof AdminAccessControlRoute
    }
    '/_manager/forms/$formType': {
      id: '/_manager/forms/$formType'
      path: '/$formType'
      fullPath: '/forms/$formType'
      preLoaderRoute: typeof ManagerFormsFormTypeRouteImport
      parentRoute: typeof ManagerFormsRoute
    }
    '/_manager/_overview/monitored-fields': {
      id: '/_manager/_overview/monitored-fields'
      path: '/monitored-fields'
      fullPath: '/monitored-fields'
      preLoaderRoute: typeof ManagerOverviewMonitoredFieldsRouteImport
      parentRoute: typeof ManagerOverviewRoute
    }
    '/_manager/_overview/dashboard': {
      id: '/_manager/_overview/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ManagerOverviewDashboardRouteImport
      parentRoute: typeof ManagerOverviewRoute
    }
    '/_manager/_overview/collection': {
      id: '/_manager/_overview/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof ManagerOverviewCollectionRouteImport
      parentRoute: typeof ManagerOverviewRoute
    }
    '/_manager/_data/mfid': {
      id: '/_manager/_data/mfid'
      path: '/mfid'
      fullPath: '/mfid'
      preLoaderRoute: typeof ManagerDataMfidRouteImport
      parentRoute: typeof ManagerDataRoute
    }
    '/_manager/_data/import': {
      id: '/_manager/_data/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ManagerDataImportRouteImport
      parentRoute: typeof ManagerDataRoute
    }
    '/_manager/_analytics/predictive': {
      id: '/_manager/_analytics/predictive'
      path: '/predictive'
      fullPath: '/predictive'
      preLoaderRoute: typeof ManagerAnalyticsPredictiveRouteImport
      parentRoute: typeof ManagerAnalyticsRoute
    }
    '/_manager/_analytics/forms-analytics': {
      id: '/_manager/_analytics/forms-analytics'
      path: '/forms-analytics'
      fullPath: '/forms-analytics'
      preLoaderRoute: typeof ManagerAnalyticsFormsAnalyticsRouteImport
      parentRoute: typeof ManagerAnalyticsRoute
    }
    '/_manager/_analytics/descriptive': {
      id: '/_manager/_analytics/descriptive'
      path: '/descriptive'
      fullPath: '/descriptive'
      preLoaderRoute: typeof ManagerAnalyticsDescriptiveRouteImport
      parentRoute: typeof ManagerAnalyticsRoute
    }
    '/_manager/_analytics/comparative': {
      id: '/_manager/_analytics/comparative'
      path: '/comparative'
      fullPath: '/comparative'
      preLoaderRoute: typeof ManagerAnalyticsComparativeRouteImport
      parentRoute: typeof ManagerAnalyticsRoute
    }
    '/_manager/forms/$formType/': {
      id: '/_manager/forms/$formType/'
      path: '/'
      fullPath: '/forms/$formType/'
      preLoaderRoute: typeof ManagerFormsFormTypeIndexRouteImport
      parentRoute: typeof ManagerFormsFormTypeRoute
    }
    '/_manager/_data/mfid/': {
      id: '/_manager/_data/mfid/'
      path: '/'
      fullPath: '/mfid/'
      preLoaderRoute: typeof ManagerDataMfidIndexRouteImport
      parentRoute: typeof ManagerDataMfidRoute
    }
    '/_manager/forms/$formType/$id': {
      id: '/_manager/forms/$formType/$id'
      path: '/$id'
      fullPath: '/forms/$formType/$id'
      preLoaderRoute: typeof ManagerFormsFormTypeIdRouteImport
      parentRoute: typeof ManagerFormsFormTypeRoute
    }
    '/_manager/_data/mfid/$mfid': {
      id: '/_manager/_data/mfid/$mfid'
      path: '/$mfid'
      fullPath: '/mfid/$mfid'
      preLoaderRoute: typeof ManagerDataMfidMfidRouteImport
      parentRoute: typeof ManagerDataMfidRoute
    }
  }
}

interface ManagerAnalyticsRouteChildren {
  ManagerAnalyticsComparativeRoute: typeof ManagerAnalyticsComparativeRoute
  ManagerAnalyticsDescriptiveRoute: typeof ManagerAnalyticsDescriptiveRoute
  ManagerAnalyticsFormsAnalyticsRoute: typeof ManagerAnalyticsFormsAnalyticsRoute
  ManagerAnalyticsPredictiveRoute: typeof ManagerAnalyticsPredictiveRoute
}

const ManagerAnalyticsRouteChildren: ManagerAnalyticsRouteChildren = {
  ManagerAnalyticsComparativeRoute: ManagerAnalyticsComparativeRoute,
  ManagerAnalyticsDescriptiveRoute: ManagerAnalyticsDescriptiveRoute,
  ManagerAnalyticsFormsAnalyticsRoute: ManagerAnalyticsFormsAnalyticsRoute,
  ManagerAnalyticsPredictiveRoute: ManagerAnalyticsPredictiveRoute,
}

const ManagerAnalyticsRouteWithChildren =
  ManagerAnalyticsRoute._addFileChildren(ManagerAnalyticsRouteChildren)

interface ManagerDataMfidRouteChildren {
  ManagerDataMfidMfidRoute: typeof ManagerDataMfidMfidRoute
  ManagerDataMfidIndexRoute: typeof ManagerDataMfidIndexRoute
}

const ManagerDataMfidRouteChildren: ManagerDataMfidRouteChildren = {
  ManagerDataMfidMfidRoute: ManagerDataMfidMfidRoute,
  ManagerDataMfidIndexRoute: ManagerDataMfidIndexRoute,
}

const ManagerDataMfidRouteWithChildren = ManagerDataMfidRoute._addFileChildren(
  ManagerDataMfidRouteChildren,
)

interface ManagerDataRouteChildren {
  ManagerDataImportRoute: typeof ManagerDataImportRoute
  ManagerDataMfidRoute: typeof ManagerDataMfidRouteWithChildren
}

const ManagerDataRouteChildren: ManagerDataRouteChildren = {
  ManagerDataImportRoute: ManagerDataImportRoute,
  ManagerDataMfidRoute: ManagerDataMfidRouteWithChildren,
}

const ManagerDataRouteWithChildren = ManagerDataRoute._addFileChildren(
  ManagerDataRouteChildren,
)

interface ManagerOverviewRouteChildren {
  ManagerOverviewCollectionRoute: typeof ManagerOverviewCollectionRoute
  ManagerOverviewDashboardRoute: typeof ManagerOverviewDashboardRoute
  ManagerOverviewMonitoredFieldsRoute: typeof ManagerOverviewMonitoredFieldsRoute
}

const ManagerOverviewRouteChildren: ManagerOverviewRouteChildren = {
  ManagerOverviewCollectionRoute: ManagerOverviewCollectionRoute,
  ManagerOverviewDashboardRoute: ManagerOverviewDashboardRoute,
  ManagerOverviewMonitoredFieldsRoute: ManagerOverviewMonitoredFieldsRoute,
}

const ManagerOverviewRouteWithChildren = ManagerOverviewRoute._addFileChildren(
  ManagerOverviewRouteChildren,
)

interface ManagerFormsFormTypeRouteChildren {
  ManagerFormsFormTypeIdRoute: typeof ManagerFormsFormTypeIdRoute
  ManagerFormsFormTypeIndexRoute: typeof ManagerFormsFormTypeIndexRoute
}

const ManagerFormsFormTypeRouteChildren: ManagerFormsFormTypeRouteChildren = {
  ManagerFormsFormTypeIdRoute: ManagerFormsFormTypeIdRoute,
  ManagerFormsFormTypeIndexRoute: ManagerFormsFormTypeIndexRoute,
}

const ManagerFormsFormTypeRouteWithChildren =
  ManagerFormsFormTypeRoute._addFileChildren(ManagerFormsFormTypeRouteChildren)

interface ManagerFormsRouteChildren {
  ManagerFormsFormTypeRoute: typeof ManagerFormsFormTypeRouteWithChildren
}

const ManagerFormsRouteChildren: ManagerFormsRouteChildren = {
  ManagerFormsFormTypeRoute: ManagerFormsFormTypeRouteWithChildren,
}

const ManagerFormsRouteWithChildren = ManagerFormsRoute._addFileChildren(
  ManagerFormsRouteChildren,
)

interface ManagerRouteChildren {
  ManagerAnalyticsRoute: typeof ManagerAnalyticsRouteWithChildren
  ManagerDataRoute: typeof ManagerDataRouteWithChildren
  ManagerOverviewRoute: typeof ManagerOverviewRouteWithChildren
  ManagerFormsRoute: typeof ManagerFormsRouteWithChildren
  ManagerSandboxRoute: typeof ManagerSandboxRoute
}

const ManagerRouteChildren: ManagerRouteChildren = {
  ManagerAnalyticsRoute: ManagerAnalyticsRouteWithChildren,
  ManagerDataRoute: ManagerDataRouteWithChildren,
  ManagerOverviewRoute: ManagerOverviewRouteWithChildren,
  ManagerFormsRoute: ManagerFormsRouteWithChildren,
  ManagerSandboxRoute: ManagerSandboxRoute,
}

const ManagerRouteWithChildren =
  ManagerRoute._addFileChildren(ManagerRouteChildren)

interface AdminAccessControlRouteChildren {
  AdminAccessControlUserManagementRoute: typeof AdminAccessControlUserManagementRoute
}

const AdminAccessControlRouteChildren: AdminAccessControlRouteChildren = {
  AdminAccessControlUserManagementRoute: AdminAccessControlUserManagementRoute,
}

const AdminAccessControlRouteWithChildren =
  AdminAccessControlRoute._addFileChildren(AdminAccessControlRouteChildren)

interface AdminConfigurationRouteChildren {
  AdminConfigurationSettingsRoute: typeof AdminConfigurationSettingsRoute
}

const AdminConfigurationRouteChildren: AdminConfigurationRouteChildren = {
  AdminConfigurationSettingsRoute: AdminConfigurationSettingsRoute,
}

const AdminConfigurationRouteWithChildren =
  AdminConfigurationRoute._addFileChildren(AdminConfigurationRouteChildren)

interface AdminOperationsRouteChildren {
  AdminOperationsActivityLogsRoute: typeof AdminOperationsActivityLogsRoute
  AdminOperationsAuditLogsRoute: typeof AdminOperationsAuditLogsRoute
  AdminOperationsBackupRoute: typeof AdminOperationsBackupRoute
}

const AdminOperationsRouteChildren: AdminOperationsRouteChildren = {
  AdminOperationsActivityLogsRoute: AdminOperationsActivityLogsRoute,
  AdminOperationsAuditLogsRoute: AdminOperationsAuditLogsRoute,
  AdminOperationsBackupRoute: AdminOperationsBackupRoute,
}

const AdminOperationsRouteWithChildren = AdminOperationsRoute._addFileChildren(
  AdminOperationsRouteChildren,
)

interface AdminOverviewRouteChildren {
  AdminOverviewDashboardRoute: typeof AdminOverviewDashboardRoute
}

const AdminOverviewRouteChildren: AdminOverviewRouteChildren = {
  AdminOverviewDashboardRoute: AdminOverviewDashboardRoute,
}

const AdminOverviewRouteWithChildren = AdminOverviewRoute._addFileChildren(
  AdminOverviewRouteChildren,
)

interface AdminRouteChildren {
  AdminAccessControlRoute: typeof AdminAccessControlRouteWithChildren
  AdminConfigurationRoute: typeof AdminConfigurationRouteWithChildren
  AdminOperationsRoute: typeof AdminOperationsRouteWithChildren
  AdminOverviewRoute: typeof AdminOverviewRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccessControlRoute: AdminAccessControlRouteWithChildren,
  AdminConfigurationRoute: AdminConfigurationRouteWithChildren,
  AdminOperationsRoute: AdminOperationsRouteWithChildren,
  AdminOverviewRoute: AdminOverviewRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManagerRoute: ManagerRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  Data_collectorRoute: Data_collectorRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
