CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_id uuid unique references auth.users(id) on delete cascade,
  user_id TEXT NOT NULL UNIQUE DEFAULT next_user_id(),
  role_id BIGINT NOT NULL REFERENCES roles(id),
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  date_of_birth DATE NOT NULL,
  -- email TEXT NOT NULL UNIQUE, -- using auth.users.email instead
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'disabled')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

