create table provinces(
    id   int generated by default as identity primary key,
    code text not null unique,
    name text not null);



create table cities_municipalities(
    id          int generated by default as identity primary key,
    province_id int not null references provinces(id),
    code        text not null unique,
    name        text not null);

create index idx_cities_province_id on cities_municipalities using btree(province_id);



create table barangays(
    id                      int generated by default as identity primary key,
    city_municipality_id    int not null references cities_municipalities(id),
    code                    text not null unique,
    name                    text not null);

create index idx_barangays_city_municipality_id on barangays using btree(city_municipality_id);


create or replace view addresses as
    select
        barangays.id as barangay_id,
        barangays.name as barangay,
        cities_municipalities.id as city_municipality_id,
        cities_municipalities.name as city_municipality,
        provinces.id as province_id,
        provinces.name as province
    from barangays
        join cities_municipalities on barangays.city_municipality_id = cities_municipalities.id
        join provinces on cities_municipalities.province_id = provinces.id;

