

create table seasons (
  id           int generated by default as identity primary key,
  start_date   date not null,
  end_date     date not null,
  semester     semester not null,
  season_year  text not null,
  unique (start_date, end_date)
);
create index idx_seasons_start_date on seasons (start_date);
create index idx_seasons_semester on seasons (semester);


CREATE TABLE mfids (
  id int generated by default as identity primary key,
  mfid text not null unique,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create table farmers (
  id                    int generated by default as identity primary key,
  first_name            text not null,
  last_name             text not null,
  gender                gender not null,
  date_of_birth         date not null,
  cellphone_no          text not null,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);


create table fields (
  id int generated by default as identity primary key,
  farmer_id int not null references farmers(id),
  barangay_id int not null references barangays(id),
  mfid text not null unique,
  location spatial.geometry(Point, 4326) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index idx_fields_farmer_id on fields using btree (farmer_id);
create index idx_fields_location on fields using gist (location);
create index idx_fields_barangay_id on fields using btree (barangay_id);
