

create table seasons (
    id           int generated by default as identity primary key,
    start_date   date not null,
    end_date     date not null,
    semester     semester not null,
    season_year  text not null,
    unique (start_date, end_date));

create index idx_seasons_start_date on seasons (start_date);

create index idx_seasons_semester on seasons (semester);

create table farmers (
    id              int generated by default as identity primary key,
    first_name      text not null,
    last_name       text not null,
    gender          gender null,
    date_of_birth   date null,
    cellphone_no    text null,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now(),
    unique(first_name, last_name));


create table fields (
    id              int generated by default as identity primary key,
    farmer_id       int not null references farmers(id),
    barangay_id     int not null references barangays(id),
    mfid_id         int not null references public.mfids(id),
    location        spatial.geometry(Point, 4326) null, --
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now(),

    unique(mfid_id)
    );

create index idx_fields_farmer_id on fields using btree (farmer_id);

create index idx_fields_location on fields using gist (location);

create index idx_fields_barangay_id on fields using btree (barangay_id);

create index idx_fields_mfid_id on public.fields(mfid_id);

