
create table collection_tasks (
    id              int generated by default as identity primary key,
    mfid_id         int NOT NULL REFERENCES public.mfids(id),
    collector_id    uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    season_id       int NOT NULL REFERENCES seasons(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    activity_type   activity_type NOT NULL,
    can_retake      boolean default false,
    retake_of       int references collection_tasks(id),
    start_date      date NOT NULL,
    end_date        date NOT NULL,
    status          text NOT NULL DEFAULT 'pending' CHECK (status in ('pending', 'completed')),
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    assigned_at     timestamptz
);

create index idx_collection_tasks_season on collection_tasks(season_id);

create index idx_collection_tasks_collector on collection_tasks(collector_id);

alter publication supabase_realtime add table collection_tasks;


create or replace function set_retake_flag()
returns trigger as $$
begin
    if new.retake_of is not null then
        update collection_tasks
        set can_retake = true
        where id = new.retake_of;
    end if;

    return new;
end;
$$ language plpgsql;


create trigger trigger_set_retake_flag
    after insert or update of retake_of
    on collection_tasks
    for each row
    execute function set_retake_flag();


create or replace function create_collection_task(
  p_mfid text,
  p_season_id int,
  p_activity_type text,
  p_collector_id uuid,
  p_start_date date,
  p_end_date date,
  p_retake_of int default null,
  p_user_id uuid default auth.uid()
)
returns int
language plpgsql
security definer
set search_path = 'public'
as $$
declare
  v_mfid_id int;
  v_task_id int;
begin
  perform set_config('app.current_user_id', p_user_id::text, true);

  select id into v_mfid_id
  from public.mfids
  where mfid = p_mfid;

  if not found then
    raise exception 'MFID "%" not found', p_mfid;
  end if;

  insert into public.collection_tasks (
    mfid_id,
    season_id,
    activity_type,
    collector_id,
    start_date,
    end_date,
    retake_of,
    assigned_at
  ) values (
    v_mfid_id,
    p_season_id,
    p_activity_type::public.activity_type,
    p_collector_id,
    p_start_date,
    p_end_date,
    p_retake_of,
    now()
  )
  returning id into v_task_id;

  return v_task_id;
end;
$$;

create or replace function update_collection_task(
  p_task_id int,
  p_collector_id uuid default null,
  p_start_date date default null,
  p_end_date date default null,
  p_user_id uuid default auth.uid()
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform set_config('app.current_user_id', p_user_id::text, true);

  update public.collection_tasks
  set
    collector_id = coalesce(p_collector_id, collector_id),
    start_date = coalesce(p_start_date, start_date),
    end_date = coalesce(p_end_date, end_date),
    updated_at = now()
  where id = p_task_id;

  if not found then
    raise exception 'Collection task % not found', p_task_id;
  end if;
end;
$$;

create or replace function schedule_core_collection_tasks(
  p_mfid text,
  p_season_id int,
  p_activity_type text,
  p_collector_id uuid,
  p_start_date date,
  p_end_date date,
  p_schedule_all boolean default false,
  p_retake_of int default null,
  p_user_id uuid default auth.uid()
)
returns int
language plpgsql
security definer
set search_path = 'public'
as $$
declare
  v_mfid_id    int;
  v_task_id    int;
  v_next_type  text;
  v_types      text[] := array[
    'cultural-management',
    'nutrient-management',
    'production'
  ];  -- order matters: first one gets +1 month, second +2 months, etc.
begin
  perform set_config('app.current_user_id', p_user_id::text, true);

  -- Resolve MFID
  select id into v_mfid_id
  from public.mfids
  where mfid = p_mfid;

  if not found then
    raise exception 'MFID "%" not found', p_mfid;
  end if;

  -- Insert the original Field Data task
  insert into public.collection_tasks (
    mfid_id, season_id, activity_type,
    collector_id, start_date, end_date,
    retake_of, assigned_at
  ) values (
    v_mfid_id, p_season_id, p_activity_type::public.activity_type,
    p_collector_id, p_start_date, p_end_date,
    p_retake_of, now()
  )
  returning id into v_task_id;

  -- If scheduling all, create the other core types (if not already present)
  if p_schedule_all and p_activity_type = 'field-data' then
    for i in 1..array_length(v_types, 1) loop
      v_next_type := v_types[i];
      if not exists (
        select 1 from public.collection_tasks
        where mfid_id  = v_mfid_id
          and season_id = p_season_id
          and activity_type = v_next_type::public.activity_type
      ) then
        insert into public.collection_tasks (
          mfid_id, season_id, activity_type,
          collector_id, start_date, end_date,
          assigned_at
        ) values (
          v_mfid_id, p_season_id, v_next_type::public.activity_type,
          p_collector_id,
          p_start_date + (i * interval '1 month'),   -- shifted start
          p_end_date   + (i * interval '1 month'),   -- shifted end
          now()
        );
      end if;
    end loop;
  end if;

  return v_task_id;
end;
$$;

create or replace function batch_schedule_core_collection_tasks(
  p_mfids text[],
  p_season_id int,
  p_collector_id uuid,
  p_start_date date,
  p_end_date date,
  p_user_id uuid default auth.uid()
)
returns void
language plpgsql
security definer
set search_path = 'public'
as $$
declare
  v_mfid      text;
  v_mfid_id   int;
  v_next_type text;
  v_types     text[] := array[
    'cultural-management',
    'nutrient-management',
    'production'
  ];
begin
  perform set_config('app.current_user_id', p_user_id::text, true);

  foreach v_mfid in array p_mfids loop
    -- Resolve MFID id
    select id into v_mfid_id from public.mfids where mfid = v_mfid;
    if not found then
      raise notice 'MFID "%" not found, skipping', v_mfid;
      continue;
    end if;

    -- Skip if field-data already exists for this MFID/season
    if exists (
      select 1 from public.collection_tasks
      where mfid_id = v_mfid_id
        and season_id = p_season_id
        and activity_type = 'field-data'
    ) then
      raise notice 'Field data already exists for mfid=%, season=%, skipping', v_mfid, p_season_id;
      continue;
    end if;

    -- Insert field-data task
    insert into public.collection_tasks (
      mfid_id, season_id, activity_type,
      collector_id, start_date, end_date, assigned_at
    ) values (
      v_mfid_id, p_season_id, 'field-data',
      p_collector_id, p_start_date, p_end_date, now()
    );

    -- Insert the other core types (if not already present)
    for i in 1..array_length(v_types, 1) loop
      v_next_type := v_types[i];
      if not exists (
        select 1 from public.collection_tasks
        where mfid_id = v_mfid_id
          and season_id = p_season_id
          and activity_type = v_next_type::public.activity_type
      ) then
        insert into public.collection_tasks (
          mfid_id, season_id, activity_type,
          collector_id, start_date, end_date, assigned_at
        ) values (
          v_mfid_id, p_season_id, v_next_type::public.activity_type,
          p_collector_id,
          p_start_date + (i * interval '1 month'),
          p_end_date   + (i * interval '1 month'),
          now()
        );
      end if;
    end loop;
  end loop;
end;
$$;

create or replace function delete_collection_task(
  p_task_id int,
  p_user_id uuid default auth.uid()
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform set_config('app.current_user_id', p_user_id::text, true);

  delete from public.collection_tasks
  where id = p_task_id;

  if not found then
    raise exception 'Collection task % not found', p_task_id;
  end if;
end;
$$;


CREATE OR REPLACE FUNCTION public.update_task_status(
    task_id INT,
    new_status TEXT DEFAULT 'completed'
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    UPDATE public.collection_tasks
    SET status = new_status,
        updated_at = NOW()
    WHERE id = task_id
      AND status = 'pending'
      AND collector_id = auth.uid();

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Task not found, already completed, or not owned by user';
    END IF;
END;
$$;
