create table field_activities(
    id                  int generated by default as identity primary key,
    field_id            int not null references fields(id),
    season_id           int not null references seasons(id),
    activity_type       activity_type not null,
    collected_by        uuid null references users(id),
    verified_by         uuid null references users(id),
    verification_status verification_status not null default 'pending',
    remarks             text null,
    image_urls          jsonb null check (jsonb_typeof(image_urls) = 'array'),
    collected_at        timestamptz null default now(),
    updated_at          timestamptz not null default now(),
    verified_at         timestamptz null,
    synced_at           timestamptz null,
    unique (field_id, season_id, activity_type));

create index idx_fa_field_id on field_activities using btree(field_id);

create index idx_fa_season_id on field_activities using btree(season_id);

create index idx_field_activities_season_field on field_activities(season_id, field_id);

create index idx_fa_season_activity_type on field_activities(season_id, activity_type);

create index idx_fa_field_data_id on field_activities(id) where activity_type = 'field-data';

create index idx_fa_cultural_management_id on field_activities(id) where activity_type = 'cultural-management';

create index idx_fa_nutrient_management_id on field_activities(id) where activity_type = 'nutrient-management';

-- create index idx_fa_crop_cut_id on field_activities(id) where activity_type = 'crop_cut';

create index idx_fa_production_id on field_activities(id) where activity_type = 'production';

create index idx_fa_monitoring_visit_id on field_activities(id) where activity_type = 'monitoring-visit';

create index idx_fa_damage_assessment_id on field_activities(id) where activity_type = 'damage-assessment';

create index idx_fa_collected_by on field_activities using btree(collected_by);

create index idx_fa_verified_by on field_activities using btree(verified_by);

create index idx_fa_collected_at on field_activities using btree(collected_at);

create index idx_fa_verification_status_pending on field_activities using btree(verification_status) where verification_status = 'pending';

create index idx_fa_image_urls_gin on field_activities using gin(image_urls jsonb_path_ops);

alter publication supabase_realtime add table field_activities;


-- utility
create or replace view seasons_with_data as
    select distinct s.*
    from seasons s
    join field_activities fa on fa.season_id = s.id;


create or replace function public.get_available_locations(p_season_id int default null)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    target_season_id int;
    result jsonb;
begin
    if p_season_id is null then
        select id into target_season_id
        from public.seasons
        order by start_date desc
        limit 1;
    else
        target_season_id := p_season_id;
    end if;

    with
        province_list as (
            select distinct p.name
            from public.field_activities fa
            join public.fields f on fa.field_id = f.id
            join public.addresses a on f.barangay_id = a.barangay_id
            join public.provinces p on a.province_id = p.id
            where fa.season_id = target_season_id
        ),

        municipality_list as (
            select distinct cm.name, p.name as province_name
            from public.field_activities fa
            join public.fields f on fa.field_id = f.id
            join public.addresses a on f.barangay_id = a.barangay_id
            join public.cities_municipalities cm on a.city_municipality_id = cm.id
            join public.provinces p on a.province_id = p.id
            where fa.season_id = target_season_id
        ),

        barangay_list as (
            select distinct b.name, cm.name as municipality_name
            from public.field_activities fa
            join public.fields f on fa.field_id = f.id
            join public.addresses a on f.barangay_id = a.barangay_id
            join public.barangays b on a.barangay_id = b.id
            join public.cities_municipalities cm on a.city_municipality_id = cm.id
            where fa.season_id = target_season_id
        )
    select jsonb_build_object(
        'provinces', coalesce((select jsonb_agg(name order by name) from province_list), '[]'::jsonb),
        'municipalities', coalesce((select jsonb_agg(jsonb_build_object('name', name, 'province', province_name) order by province_name, name) from municipality_list), '[]'::jsonb),
        'barangays', coalesce((select jsonb_agg(jsonb_build_object('name', name, 'municipality', municipality_name) order by municipality_name, name) from barangay_list), '[]'::jsonb)
    ) into result;

    return result;
end;
$$;
