create table monitoring_visits(
    id                      int generated by default as identity primary key,
    date_monitored          date not null,
    crop_stage              text not null,
    soil_moisture_status    text not null,
    avg_plant_height        double precision null);


create table field_activities(
    id                  int generated by default as identity primary key,
    collection_task_id  int null references collection_tasks(id),
    monitoring_visit_id int null references monitoring_visits(id) on delete restrict,
    field_id            int not null references fields(id),
    season_id           int not null references seasons(id),
    activity_type       activity_type not null,
    collected_by        uuid null references users(id), -- to be removed
    verified_by         uuid null references users(id),
    verification_status verification_status not null default 'pending',
    remarks             text null,
    image_urls          jsonb null check (jsonb_typeof(image_urls) = 'array'),
    collected_at        timestamptz null default now(), -- to be removed
    updated_at          timestamptz not null default now(),
    verified_at         timestamptz null,
    synced_at           timestamptz null,
    unique (collection_task_id));

create index idx_fa_field_id on field_activities using btree(field_id);

create index idx_fa_season_id on field_activities using btree(season_id);

create index idx_field_activities_season_field on field_activities(season_id, field_id);

create index idx_fa_season_activity_type on field_activities(season_id, activity_type);

create index idx_fa_field_data_id on field_activities(id) where activity_type = 'field-data';

create index idx_fa_cultural_management_id on field_activities(id) where activity_type = 'cultural-management';

create index idx_fa_nutrient_management_id on field_activities(id) where activity_type = 'nutrient-management';

create index idx_fa_production_id on field_activities(id) where activity_type = 'production';

create index idx_fa_monitoring_visit_id on field_activities(id) where activity_type = 'monitoring-visit';

create index idx_fa_damage_assessment_id on field_activities(id) where activity_type = 'damage-assessment';

create index idx_fa_collected_by on field_activities using btree(collected_by);

create index idx_fa_verified_by on field_activities using btree(verified_by);

create index idx_fa_collected_at on field_activities using btree(collected_at);

create index idx_fa_verification_status_pending on field_activities using btree(verification_status) where verification_status = 'pending';

create index idx_fa_image_urls_gin on field_activities using gin(image_urls jsonb_path_ops);

alter publication supabase_realtime add table field_activities;

