
-- metadata 1 (field data)
create table field_plannings (
  id                                int primary key references field_activities(id) unique,
  land_preparation_start_date       date not null,
  est_crop_establishment_date       date not null,
  est_crop_establishment_method     text not null,
  total_field_area_ha               double precision not null,
  soil_type                         text null, -- N/A
  current_field_condition           text not null
);
create index idx_fp_prep_start_date on field_plannings(land_preparation_start_date);
create index idx_fp_establish_date on field_plannings(est_crop_establishment_date);


-- metadata 2 (cultural management)
create table crop_establishments (
  id                                int primary key references field_activities(id) unique,
  ecosystem                         text not null,
  monitoring_field_area_sqm         double precision not null,
  actual_land_preparation_method    text not null,
  actual_crop_establishment_date    date not null,
  actual_crop_establishment_method  text not null,

  -- if transplanted
  sowing_date                       date null,
  seedling_age_at_transplanting     smallint null check (seedling_age_at_transplanting between 1 and 100),
  distance_between_plant_row_1      double precision null,
  distance_between_plant_row_2      double precision null,
  distance_between_plant_row_3      double precision null,
  distance_within_plant_row_1       double precision null,
  distance_within_plant_row_2       double precision null,
  distance_within_plant_row_3       double precision null,

  -- if direct-seeded
  seeding_rate_kg_ha                double precision null,
  direct_seeding_method             text null,
  num_plants_1                      smallint null,
  num_plants_2                      smallint null,
  num_plants_3                      smallint null,

  rice_variety                      text not null,
  rice_variety_no                   text null,
  rice_variety_maturity_duration    smallint not null,
  seed_class                        text not null
  -- source_of_seed                    text not null, -- seed_producer, etc.
  -- crop_growth_stage                 text not null -- flowering, tillering, etc.
);
create index idx_ce_actual_date on crop_establishments(actual_crop_establishment_date);
create index idx_ce_variety on crop_establishments(rice_variety);


-- metadata 3 (nutrient management 1/2)
create table fertilization_records (
  id                                int primary key references field_activities(id) unique,
  applied_area_sqm                  double precision not null
);
create index idx_fr_id on fertilization_records using btree (id);


-- metadata 3 (nutrient management 2/2)
create table fertilizer_applications (
  id                                int generated by default as identity primary key,
  fertilization_record_id           int not null references fertilization_records(id),
  fertilizer_type                   text not null,
  brand                             text not null,
  nitrogen_content_pct              double precision not null,
  phosphorus_content_pct            double precision not null,
  potassium_content_pct             double precision not null,
  amount_applied                    double precision not null,
  amount_unit                       text not null,
  crop_stage_on_application         text not null
);
create index idx_fa_records_id on fertilizer_applications(fertilization_record_id);


-- metadata 4 (production)
create table harvest_records (
  id                                int primary key references field_activities(id) unique,
  harvest_date                      date not null,
  harvesting_method                 harvesting_method not null,
  bags_harvested                    int not null,
  avg_bag_weight_kg                 double precision not null,
  area_harvested_ha                 double precision not null,
  irrigation_supply                 irrigation_supply not null
);
create index idx_hr_harvest_date on harvest_records(harvest_date);

-- optional
create table damage_assessments(
  id                                int primary key references field_activities(id) unique,
  cause                             text not null,
  crop_stage                        text not null,
  soil_type                         text not null,
  severity                          text not null,
  affected_area_ha                  double precision not null,
  observed_pest                     text null
);

-- optional
create table monitoring_visits (
  id                                int primary key references field_activities(id) unique,
  date_monitored                    date not null,
  crop_stage                        text not null,
  soil_moisture_status              text not null,
  avg_plant_height                  double precision null
);
