create table public.notifications (
    id int generated by default as identity primary key,
    user_id uuid null references users(id) on delete cascade,
    title text not null,
    target_role text,
    message text not null,
    type text not null, -- 'task_assigned', 'verification_approved', 'verification_rejected', 'form_submitted'
    related_entity_id text, -- optional: task id, activity id, etc.
    is_read boolean default false,
    created_at timestamptz default now()
);

create index idx_notifications_user_id on public.notifications(user_id);
create index idx_notifications_created_at on public.notifications(created_at desc);
create index idx_notifications_target_role on public.notifications(target_role);

alter publication supabase_realtime add table public.notifications;



create or replace function notify_new_task()
returns trigger
language plpgsql
security definer
as $$
begin
    insert into public.notifications (user_id, target_role,title, message, type, related_entity_id)
    values (
        new.collector_id,
        'data_collector',
        'New Task Assigned',
        format('You have a new %s task to collect.', new.activity_type),
        'task_assigned',
        new.id::text
    );
    return new;
end;
$$;

create trigger trigger_notify_new_task
    after insert on collection_tasks
    for each row
    execute function notify_new_task();



create or replace function notify_verification_status()
returns trigger
language plpgsql
security definer
as $$
begin
    if new.verification_status != old.verification_status then
        if new.verification_status = 'approved' then
            insert into public.notifications (user_id, target_role, title, message, type, related_entity_id)
            values (
                new.collected_by,
                'data_collector',
                'Form Approved',
                format('Your %s form has been approved.', new.activity_type),
                'verification_approved',
                new.id::text
            );
        elsif new.verification_status = 'rejected' then
            insert into public.notifications (user_id, target_role, title, message, type, related_entity_id)
            values (
                new.collected_by,
                'data_collector',
                'Form Rejected',
                format('Your %s form has been rejected. Please check remarks.', new.activity_type),
                'verification_rejected',
                new.id::text
            );
        end if;
    end if;
    return new;
end;
$$;

create trigger trigger_notify_verification
    after update on field_activities
    for each row
    execute function notify_verification_status();


create or replace function notify_form_submitted()
returns trigger
language plpgsql
security definer
as $$
declare
    field_mfid text;
begin
    if current_setting('app.import_mode', true) = 'true' then
        return new;
    end if;

    select m.mfid into field_mfid
    from fields f
    join mfids m on f.mfid_id = m.id
    where f.id = new.field_id;

    insert into public.notifications (target_role, title, message, type, related_entity_id)
    values (
        'data_manager',
        'Form Submitted',
        format('A %s form has been submitted for MFID %s.', new.activity_type, field_mfid),
        'form_submitted',
        new.id::text
    );
    return new;
end;
$$;

create trigger trigger_notify_form_submitted
    after insert on field_activities
    for each row
    execute function notify_form_submitted();


create or replace function notify_overdue_tasks()
returns void
language plpgsql
security definer
as $$
declare
  overdue_task record;
begin
  for overdue_task in
    select t.id, t.mfid_id, t.activity_type, t.end_date
    from collection_tasks t
    where t.end_date < current_date
      and t.status != 'completed'
      and not exists (                  -- no existing notification for this task
        select 1 from public.notifications n
        where n.related_entity_id = t.id::text
          and n.type = 'task_overdue'
      )
  loop
    insert into public.notifications (
      target_role, title, message, type, related_entity_id
    ) values (
      'data_manager',
      'Overdue Collection Task',
      format(
        'Task %s for MFID %s is overdue (end date: %s).',
        overdue_task.activity_type,
        (select m.mfid from mfids m where m.id = overdue_task.mfid_id),
        overdue_task.end_date
      ),
      'task_overdue',
      overdue_task.id::text
    );
  end loop;
end;
$$;

select cron.schedule(
  'check-overdue-tasks',
  '0 9 * * *',
  'select notify_overdue_tasks();'
);
